# Generated by Django 5.1.2 on 2024-11-08 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamapp', '0002_videoplaytime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduler',
            name='title',
        ),
        migrations.AddField(
            model_name='scheduler',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='steamapp.lesson'),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='steamapp.module'),
        ),
        migrations.DeleteModel(
            name='VideoPlayTime',
        ),
    ]
