# Generated by Django 5.1.2 on 2024-11-04 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamapp', '0002_alter_modulequestion_marks_exam_examquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='steamapp.exam'),
        ),
    ]
