# Generated by Django 5.1.2 on 2024-11-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamapp', '0004_studentattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
