# Generated by Django 5.1.2 on 2024-11-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamapp', '0004_schedulerstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulerstatus',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
